# Service
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgresql
  name: postgresql
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      volumes:
        - name: recario-storage
          persistentVolumeClaim:
            claimName: recario-csv-pvc
      containers:
      - image: postgres:12.3
        resources:
          requests:
            cpu: "3"
            memory: "4.5Gi"
        name: postgresql
        command:
          - "./docker-entrypoint.sh"
          - "-c"
          - "max_connections=200"
          - "-c"
          - "shared_buffers=1280MB"
          - "-c"
          - "effective_cache_size=3840MB"
          - "-c"
          - "maintenance_work_mem=320MB"
          - "-c"
          - "checkpoint_completion_target=0.7"
          - "-c"
          - "wal_buffers=16MB"
          - "-c"
          - "default_statistics_target=100"
          - "-c"
          - "random_page_cost=1.1"
          - "-c"
          - "effective_io_concurrency=200"
          - "-c"
          - "work_mem=3276kB"
          - "-c"
          - "min_wal_size=1GB"
          - "-c"
          - "max_wal_size=4GB"
          - "-c"
          - "max_worker_processes=3"
          - "-c"
          - "max_parallel_workers_per_gather=2"
          - "-c"
          - "max_parallel_workers=2"
          - "-c"
          - "max_parallel_maintenance_workers=2"
        envFrom:
          - configMapRef:
              name: rails-env-config
        volumeMounts:
          - mountPath: "/var/lib/postgresql/data"
            subPath: "postgres-data"
            name: recario-storage
          - mountPath: "/var/backups"
            subPath: "postgres-backups"
            name: recario-storage
