# Worker Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpush
  labels:
    app: rpush
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rpush
  template:
    metadata:
      labels:
        app: rpush
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: rails-env-config
        image: recario/server:latest
        name: rpush
        command: ["bundle", "exec", "rpush", "start", "-f"]
