# Worker Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: urls-sidekiq
  labels:
    app: urls-sidekiq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: urls-sidekiq
  template:
    metadata:
      labels:
        app: urls-sidekiq
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: urls-env-config
        image: recario/urls:latest
        name: urls-sidekiq
        command: [
          "bundle",
          "exec",
          "sidekiq",
          "-e",
          "development",
          "-r",
          "./config/application.rb",
          "-c",
          "16",
          "-q",
          "provider-auto-ria-scraper, 10",
          "-q",
          "provider-auto-ria-actualizer, 1000",
          "-q",
          "provider-auto-ria-crawler, 100"
        ]
      initContainers:
        - name: db-create-migrate
          image: recario/urls:latest
          command: ["bundle", "exec", "rake", "db:create", "db:migrate"]
          envFrom:
            - configMapRef:
                name: urls-env-config


